spring:
  application:
    name: ahillary-invest

server:
#  port: ${APP_PORT}
  port: 8080
  servlet:
    context-path: /v1

logging:
  level:
    ROOT: INFO
    liquibase: INFO
    org.springframework:
      boot: INFO
      web: INFO